// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySinhVien.Data;

#nullable disable

namespace QuanLiSinhVien.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327134854_AddBangMonTienQuyet")]
    partial class AddBangMonTienQuyet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySinhVien.Models.GiangVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HocHamHocVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KhoaBoMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaGV");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.KetQuaHocTap", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLHP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemQuaTrinh")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemTongKet")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaSV", "MaLHP");

                    b.ToTable("KetQuaHocTaps");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.LopHocPhan", b =>
                {
                    b.Property<string>("MaLHP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMH")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDauDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThucDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("Thu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TietBatDau")
                        .HasColumnType("int");

                    b.HasKey("MaLHP");

                    b.ToTable("LopHocPhans");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiMon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoTietLyThuyet")
                        .HasColumnType("int");

                    b.Property<int?>("SoTietThucHanh")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMH");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.MonTienQuyet", b =>
                {
                    b.Property<string>("MaMH")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaMHTQ")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.HasKey("MaMH", "MaMHTQ");

                    b.ToTable("MonTienQuyet");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSV");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
